#担当：石森
server_port: 8080
dsn: "root:rootpass@tcp(mysql_container:3306)/optim_dev"
refresh_token_expiration: 30
access_token_expiration: 30
refresh_token_secret: "secret_key_for_refresh"
access_token_secret: "secret_key"
read_timeout: 30
read_header_timeout: 30 
write_timeout: 30
idle_timeout: 30
